input_size: 224

model:
  name: efficientnet_b2
  pretrained: false 
  num_classes: 20
  freeze_base: false

train:
  batch_size: 32 #32 for efficient net
  epochs: 30
  lr: 0.0005
  optimizer: adam
  weight_decay: 0.0001
  val_split: 0.15
  seed: 42